name: Compare changes on pull request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  compare_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          repository: ${{ github.event.repository.full_name }}

      - name: Fetch pull request head ref
        run: |
          git fetch https://github.com/${{ github.event.pull_request.head.repo.full_name }}.git ${{ github.event.pull_request.head.ref }}
          git checkout FETCH_HEAD

      - name: Create temporary branch
        run: |
          git checkout -b temp_branch

      - name: Compare changes
        run: |
          changed_files=$(git diff --name-only dev temp_branch)
          echo "Changed files: $changed_files"

      - name: Delete temporary branch
        run: |
          git checkout dev
          git branch -D temp_branch
