name: WPCS check

on: 
  pull_request_target
    
jobs:
  phpcs:
      name: WPCS
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        
        - name: Fetch all branches
          run: git fetch --all --prune
          
        - name: Check changed files
          id: changed-files
          run: |
            base=$(echo "${{ github.event.pull_request.base.repo.full_name }}" | tr '[:upper:]' '[:lower:]')
            head=$(echo "${{ github.event.pull_request.head.repo.full_name }}" | tr '[:upper:]' '[:lower:]')
            compare="https://github.com/$base/compare/$head"
            files=$(curl --silent --location $compare.diff | grep \\.php$ | cut -d ' ' -f 3 | cut -c 3- | tr '\n' ' ')
            echo "::set-output name=files::$files"
        
        - name: Changed File Print
          run: echo "${{ steps.changed-files.outputs.files }}"
            
        - name: WPCS check
          if: ${{ steps.changed-files.outputs.changed_files > 0 }}
          uses: 10up/wpcs-action@stable
          with:
            repo_branch: 'dev' # Branch of Standard repository
            paths: "${{ steps.changed-files.outputs.files }}" # Paths to check, space separated like ./views ./controllers
            excludes: '' # Paths to excludes, space separated
            standard: 'WordPress' # Coding standard
            enable_warnings: 'false' # Enable checking for warnings (-w)
            use_local_config: 'false' # Use local config if available
            extra_args: '-d error_reporting="E_ALL&~E_DEPRECATED"'
