name: PHP Coding Standards Check

on:
  pull_request:
    types: [opened]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Check for PHP files changes
        run: |
          php_files=$(git diff --name-only ${{ github.base_ref }} ${{ github.head_ref }} --diff-filter=d -- '*.php')
          if [ -n "$php_files" ]; then
            echo "Changed PHP files:"
            echo "$php_files"
            composer install
            vendor/bin/phpcs --standard=PSR4 $php_files
          else
            echo "No PHP files changes"
          fi
