name: WPCS check

on: pull_request

jobs:
  phpcs:
      name: WPCS
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        
        - name: Fetch all branches
          run: git fetch --all
          
        - name: Check changed files
          id: changed-files
          run: |
            echo "$(git diff --name-only --diff-filter=ACMRTUXB origin/dev..origin/${{ github.head_ref }} | grep \\.php$ | tr '\n' ' ')" >> $GITHUB_ENV
        
        - name: Changed File Print
          run: echo "${{ env.CHANGED_FILES }}"
            
        - name: WPCS check
          uses: 10up/wpcs-action@stable
          with:
            repo_branch: 'dev' # Branch of Standard repository
            paths: "${{ env.CHANGED_FILES }}" # Paths to check, space separated like ./views ./controllers
            excludes: '' # Paths to excludes, space separated
            standard: 'WordPress' # Coding standard
            enable_warnings: 'false' # Enable checking for warnings (-w)
            use_local_config: 'false' # Use local config if available
            extra_args: '-d error_reporting="E_ALL&~E_DEPRECATED"'
