name: WPCS check

on: pull_request

jobs:
  phpcs:
      name: WPCS
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: WPCS check
          uses: 10up/wpcs-action@stable
          with:
            enable_warnings: 'false' # Enable checking for warnings (-w)
            paths: './views'
            standard: 'WordPress'
            repo_branch: 'master' # Branch of Standard repository
            use_local_config: 'false' # Use local config if available
